[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
; Serial upload/monitor settings
; Use USB CDC (auto-detected) for upload and monitor. If auto-detect fails,
; replace the value with your port, e.g. on Windows use COM3, on Linux use /dev/ttyACM0
upload_port = auto
monitor_port = auto
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1